// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqKHSI-Jw9XRqOUq3lLOq5OWD5ewHg0CA',
    appId: '1:697210776189:web:0084df908f13d4eb4b5f14',
    messagingSenderId: '697210776189',
    projectId: 'heavy-6c072',
    authDomain: 'heavy-6c072.firebaseapp.com',
    databaseURL: 'https://heavy-6c072.firebaseio.com',
    storageBucket: 'heavy-6c072.appspot.com',
    measurementId: 'G-JPZFQTQD1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCumxP23V-O118DLsXuWd4DUYYwZCsL3ms',
    appId: '1:697210776189:android:aff1e338e3d769184b5f14',
    messagingSenderId: '697210776189',
    projectId: 'heavy-6c072',
    databaseURL: 'https://heavy-6c072.firebaseio.com',
    storageBucket: 'heavy-6c072.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG7SfryxKNDdCMxLeo8_3DTZn2vnN7N3g',
    appId: '1:697210776189:ios:97b7abc324319d974b5f14',
    messagingSenderId: '697210776189',
    projectId: 'heavy-6c072',
    databaseURL: 'https://heavy-6c072.firebaseio.com',
    storageBucket: 'heavy-6c072.appspot.com',
    iosBundleId: 'com.kidsecure.kidSecure',
  );

}